/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedEventsRouteImport } from './routes/_authenticated/events'
import { Route as AuthenticatedDeploymentsRouteImport } from './routes/_authenticated/deployments'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedApplicationsRouteImport } from './routes/_authenticated/applications'
import { Route as AuthenticatedAlertsRouteImport } from './routes/_authenticated/alerts'
import { Route as AuthenticatedEventsIdRouteImport } from './routes/_authenticated/events.$id'
import { Route as AuthenticatedDeploymentsIdRouteImport } from './routes/_authenticated/deployments.$id'
import { Route as AuthenticatedApplicationsIdRouteImport } from './routes/_authenticated/applications.$id'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedEventsRoute = AuthenticatedEventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDeploymentsRoute =
  AuthenticatedDeploymentsRouteImport.update({
    id: '/deployments',
    path: '/deployments',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedApplicationsRoute =
  AuthenticatedApplicationsRouteImport.update({
    id: '/applications',
    path: '/applications',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAlertsRoute = AuthenticatedAlertsRouteImport.update({
  id: '/alerts',
  path: '/alerts',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedEventsIdRoute = AuthenticatedEventsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AuthenticatedEventsRoute,
} as any)
const AuthenticatedDeploymentsIdRoute =
  AuthenticatedDeploymentsIdRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => AuthenticatedDeploymentsRoute,
  } as any)
const AuthenticatedApplicationsIdRoute =
  AuthenticatedApplicationsIdRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => AuthenticatedApplicationsRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/alerts': typeof AuthenticatedAlertsRoute
  '/applications': typeof AuthenticatedApplicationsRouteWithChildren
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/deployments': typeof AuthenticatedDeploymentsRouteWithChildren
  '/events': typeof AuthenticatedEventsRouteWithChildren
  '/settings': typeof AuthenticatedSettingsRoute
  '/applications/$id': typeof AuthenticatedApplicationsIdRoute
  '/deployments/$id': typeof AuthenticatedDeploymentsIdRoute
  '/events/$id': typeof AuthenticatedEventsIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/alerts': typeof AuthenticatedAlertsRoute
  '/applications': typeof AuthenticatedApplicationsRouteWithChildren
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/deployments': typeof AuthenticatedDeploymentsRouteWithChildren
  '/events': typeof AuthenticatedEventsRouteWithChildren
  '/settings': typeof AuthenticatedSettingsRoute
  '/applications/$id': typeof AuthenticatedApplicationsIdRoute
  '/deployments/$id': typeof AuthenticatedDeploymentsIdRoute
  '/events/$id': typeof AuthenticatedEventsIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/_authenticated/alerts': typeof AuthenticatedAlertsRoute
  '/_authenticated/applications': typeof AuthenticatedApplicationsRouteWithChildren
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/deployments': typeof AuthenticatedDeploymentsRouteWithChildren
  '/_authenticated/events': typeof AuthenticatedEventsRouteWithChildren
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/applications/$id': typeof AuthenticatedApplicationsIdRoute
  '/_authenticated/deployments/$id': typeof AuthenticatedDeploymentsIdRoute
  '/_authenticated/events/$id': typeof AuthenticatedEventsIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/alerts'
    | '/applications'
    | '/dashboard'
    | '/deployments'
    | '/events'
    | '/settings'
    | '/applications/$id'
    | '/deployments/$id'
    | '/events/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/alerts'
    | '/applications'
    | '/dashboard'
    | '/deployments'
    | '/events'
    | '/settings'
    | '/applications/$id'
    | '/deployments/$id'
    | '/events/$id'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/login'
    | '/_authenticated/alerts'
    | '/_authenticated/applications'
    | '/_authenticated/dashboard'
    | '/_authenticated/deployments'
    | '/_authenticated/events'
    | '/_authenticated/settings'
    | '/_authenticated/applications/$id'
    | '/_authenticated/deployments/$id'
    | '/_authenticated/events/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/events': {
      id: '/_authenticated/events'
      path: '/events'
      fullPath: '/events'
      preLoaderRoute: typeof AuthenticatedEventsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/deployments': {
      id: '/_authenticated/deployments'
      path: '/deployments'
      fullPath: '/deployments'
      preLoaderRoute: typeof AuthenticatedDeploymentsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/applications': {
      id: '/_authenticated/applications'
      path: '/applications'
      fullPath: '/applications'
      preLoaderRoute: typeof AuthenticatedApplicationsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/alerts': {
      id: '/_authenticated/alerts'
      path: '/alerts'
      fullPath: '/alerts'
      preLoaderRoute: typeof AuthenticatedAlertsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/events/$id': {
      id: '/_authenticated/events/$id'
      path: '/$id'
      fullPath: '/events/$id'
      preLoaderRoute: typeof AuthenticatedEventsIdRouteImport
      parentRoute: typeof AuthenticatedEventsRoute
    }
    '/_authenticated/deployments/$id': {
      id: '/_authenticated/deployments/$id'
      path: '/$id'
      fullPath: '/deployments/$id'
      preLoaderRoute: typeof AuthenticatedDeploymentsIdRouteImport
      parentRoute: typeof AuthenticatedDeploymentsRoute
    }
    '/_authenticated/applications/$id': {
      id: '/_authenticated/applications/$id'
      path: '/$id'
      fullPath: '/applications/$id'
      preLoaderRoute: typeof AuthenticatedApplicationsIdRouteImport
      parentRoute: typeof AuthenticatedApplicationsRoute
    }
  }
}

interface AuthenticatedApplicationsRouteChildren {
  AuthenticatedApplicationsIdRoute: typeof AuthenticatedApplicationsIdRoute
}

const AuthenticatedApplicationsRouteChildren: AuthenticatedApplicationsRouteChildren =
  {
    AuthenticatedApplicationsIdRoute: AuthenticatedApplicationsIdRoute,
  }

const AuthenticatedApplicationsRouteWithChildren =
  AuthenticatedApplicationsRoute._addFileChildren(
    AuthenticatedApplicationsRouteChildren,
  )

interface AuthenticatedDeploymentsRouteChildren {
  AuthenticatedDeploymentsIdRoute: typeof AuthenticatedDeploymentsIdRoute
}

const AuthenticatedDeploymentsRouteChildren: AuthenticatedDeploymentsRouteChildren =
  {
    AuthenticatedDeploymentsIdRoute: AuthenticatedDeploymentsIdRoute,
  }

const AuthenticatedDeploymentsRouteWithChildren =
  AuthenticatedDeploymentsRoute._addFileChildren(
    AuthenticatedDeploymentsRouteChildren,
  )

interface AuthenticatedEventsRouteChildren {
  AuthenticatedEventsIdRoute: typeof AuthenticatedEventsIdRoute
}

const AuthenticatedEventsRouteChildren: AuthenticatedEventsRouteChildren = {
  AuthenticatedEventsIdRoute: AuthenticatedEventsIdRoute,
}

const AuthenticatedEventsRouteWithChildren =
  AuthenticatedEventsRoute._addFileChildren(AuthenticatedEventsRouteChildren)

interface AuthenticatedRouteChildren {
  AuthenticatedAlertsRoute: typeof AuthenticatedAlertsRoute
  AuthenticatedApplicationsRoute: typeof AuthenticatedApplicationsRouteWithChildren
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedDeploymentsRoute: typeof AuthenticatedDeploymentsRouteWithChildren
  AuthenticatedEventsRoute: typeof AuthenticatedEventsRouteWithChildren
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAlertsRoute: AuthenticatedAlertsRoute,
  AuthenticatedApplicationsRoute: AuthenticatedApplicationsRouteWithChildren,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedDeploymentsRoute: AuthenticatedDeploymentsRouteWithChildren,
  AuthenticatedEventsRoute: AuthenticatedEventsRouteWithChildren,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
